version: '3'

services:
  trinket-gym-pg:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=trinket-gym